In [1]:
import numpy as np

In [2]:
array1 = np.array([[1, 58, 107, 69], [216, 14, 25, 78]], dtype = np.uint8) #2 Boyutlu Array Oluşturma
array1

array([[  1,  58, 107,  69],
       [216,  14,  25,  78]], dtype=uint8)

In [3]:
array1.shape

(2, 4)

In [4]:
array1.size

8

In [5]:
satırSayisi = array1.shape[0]
sutunSayisi = array1.shape[1]

In [6]:
satırSayisi

2

In [7]:
sutunSayisi

4

In [8]:
array1[0,2]

107

In [9]:
array1[1,3]

78

In [10]:
array1[:,:]

array([[  1,  58, 107,  69],
       [216,  14,  25,  78]], dtype=uint8)

In [11]:
array1[0:1, 1:]

array([[ 58, 107,  69]], dtype=uint8)

In [12]:
array1[0:2, 2:3]

array([[107],
       [ 25]], dtype=uint8)

In [13]:
array2 = np.array([[[1, 2, 3], [4, 5, 6]], 
                   [[7, 8, 9], [10, 11, 12]], 
                   [[13, 14, 15], [16, 17, 18]]], dtype=int)

In [14]:
array2

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [15]:
array2.shape

(3, 2, 3)

In [16]:
array2.size

18

In [17]:
katmanSayisi = array2.shape[0]
herBirKatmanınSatırSayisi = array2.shape[1]
herBirKatmanınSutunSayisi = array2.shape[2]

In [18]:
katmanSayisi

3

In [19]:
herBirKatmanınSatırSayisi

2

In [20]:
herBirKatmanınSutunSayisi

3

In [21]:
array2[0][1][1]

5

In [29]:
array2[2,1,2]

18

In [31]:
array2[0:1, 0:2, 1:]

array([[[2, 3],
        [5, 6]]])

In [32]:
array2[0:2, 0:1, :]

array([[[1, 2, 3]],

       [[7, 8, 9]]])