In [1]:
import numpy as np

In [19]:
array1 = np.array([10, 20, 30, 40, 50])
array1

array([10, 20, 30, 40, 50])

In [20]:
array1[2]

30

In [21]:
array1[::-1]

array([50, 40, 30, 20, 10])

In [ ]:
array2 = np.array([[10, 20, 30, 40, 50],
                   [60, 70, 80, 90, 95]])
array2

In [23]:
array2[1,3]

90

In [24]:
array2[:,2:3]

array([[30],
       [80]])

In [25]:
array3 = np.array([[[5, 7, 9, 11],
                    [13, 15, 17, 19]],
                   
                  [[21, 23, 25, 27],
                   [29, 31, 33, 35]],
                   
                  [[37, 39, 41, 43],
                   [45, 47, 49, 51]]])
array3

array([[[ 5,  7,  9, 11],
        [13, 15, 17, 19]],

       [[21, 23, 25, 27],
        [29, 31, 33, 35]],

       [[37, 39, 41, 43],
        [45, 47, 49, 51]]])

In [26]:
array3[1, 0, 2]

25

In [27]:
array3[0:2, 0:1, 2:3]

array([[[ 9]],

       [[25]]])